// parameters.h - Common adjustable parameters for the project
#ifndef PARAMETERS_H
#define PARAMETERS_H

// UART configuration
#define UART_BUFFER_SIZE 256

// Accelerometer Parameters
#define ACCEL_G 9.80665f
#define ACCEL_DEVIATION_MULTIPLIER 0.1f
#define ACCEL_DEVIATION_THRESHOLD (ACCEL_DEVIATION_MULTIPLIER * ACCEL_G)

#define TRANSIENT_THS_THRESHOLD 1
#define TRANSIENT_THS_DBCNTM (0 << 7)
#define TRANSIENT_THRESHOLD_VALUE (TRANSIENT_THS_DBCNTM | (TRANSIENT_THS_THRESHOLD << 1))

#define ACCEL_MOTION_THRESHOLD 9
#define ACCEL_MOTION_DBCNTM (0 << 7)
#define ACCEL_MOTION_THRESHOLD_VALUE (ACCEL_MOTION_DBCNTM | (ACCEL_MOTION_THRESHOLD << 1))

#define ACCEL_MOTION_DEBOUNCE_COUNT 1
#define ACCEL_TRANSIENT_DEBOUNCE_COUNT 1

#define ASLP_COUNT 255

#define MOTION_TIME_THRESHOLD_MS 10000
#define NO_MOTION_TIME_THRESHOLD_MS 300000

// LED Parameters
#define LED_THREE_BLINKS_ON_TIME_MS 200
#define LED_THREE_BLINKS_OFF_TIME_MS 200
#define LED_THREE_BLINKS_BRIGHTNESS 50
#define LED_THREE_BLINKS_COUNT 3

#define LED_DOUBLE_BLINK_ON_TIME_MS 400
#define LED_DOUBLE_BLINK_OFF_TIME_MS 400
#define LED_DOUBLE_BLINK_BRIGHTNESS 80
#define LED_DOUBLE_BLINK_COUNT 2

#define LED_FADE_UPDATE_TIME_MS 10
#define LED_FADE_MAX_BRIGHTNESS 100

/* Button Controller Parameters */
#define BUTTON_DEBOUNCE_TIME_MS    50U
#define BUTTON_MULTI_PRESS_GAP_MS  500U
#define BUTTON_LONG_PRESS_TIME_MS  3000U

/* Posture Controller Parameters */
#define POSTURE_DEFAULT_THRESHOLD_ANGLE_RAD (20.0f * (M_PI / 180.0f))
#define POSTURE_EMA_ALPHA                    0.5f
#define POSTURE_TRANSITION_TIME_MS           1000U

#endif // PARAMETERS_H 